foodOnline/urls.py
from django.contrib import admin
from django.urls import path , include
from . import views
from django.conf import settings
from django.conf.urls.static import static
from marketplace import views as mplace_views
urlpatterns = [
    path("admin/", admin.site.urls),
    path('' , views.home ,name='home'),
    path('accounts/' , include('accounts.urls')),
    path('vendor/' ,include('vendor.urls')),
    path('marketplace/' , include('marketplace.urls')),
    path('cart/' ,mplace_views.cart , name='cart'),
    #Search
    path('search/',mplace_views.search ,name = 'search'),
    path('customer/' , include('customers.urls')),
    path('checkout/' , mplace_views.checkout , name='checkout'),
    path('orders/' , include('orders.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('place_order' , views.place_order , name='place_order'),
    path('payments/' , views.payments , name = 'payments'),
    path('order_complete/' , views.order_complete ,name ='order_complete'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser , BaseUserManager
from django.db.models.signals import post_save , pre_save
from django.dispatch import receiver
from django.contrib.gis.db import models as gismodels
from django.contrib.gis.geos import Point

class UserManager(BaseUserManager):
    def create_user(self , first_name , last_name , username , email , password=None):
        if not email:
            raise ValueError("User Must have an Email Address")
        if not username:
            raise ValueError('user must have Username')
        user = self.model(
            email = self.normalize_email(email),
            username = username,
            first_name = first_name,
            last_name = last_name,
        )
        user.set_password(password)
        user.save(using= self._db)
        return user
    def create_superuser(self , first_name , last_name , email, username ,password):
        user = self.create_user(
            email = self.normalize_email(email),
            username = username,
            password = password,
            first_name = first_name,
            last_name = last_name,
        )
        user.is_admin = True
        user.is_active =True
        user.is_staff = True
        user.is_superadmin = True
        user.save(using= self._db)
        return user

# Create your models here.
class User(AbstractBaseUser):
    RESTAURANT = 1
    CUSTOMER = 2
    ROLE_CHOICES = (
        (RESTAURANT , "Restaurant"),
        (CUSTOMER , "Customer"),
    )
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    username = models.CharField(max_length=50 ,unique=True)
    email = models.EmailField(max_length=100 , unique=True)
    phone_number = models.CharField(max_length=50)
    role = models.PositiveSmallIntegerField(choices=ROLE_CHOICES , blank=True , null=True)

    # required
    date_joined = models.DateTimeField(auto_now_add=True)
    last_login = models.DateTimeField(auto_now_add=True)
    is_admin = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=False)
    is_superadmin = models.BooleanField(default=False)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username' , 'first_name' , 'last_name']
    objects = UserManager()

    def __str__(self):
        return self.email

    def has_perm(self , perm , obj=None):
        return self.is_admin

    def has_module_perms(self , add_label):
        return True
    
    def get_role(self):
        if self.role == 1:
            user_role = 'Restaurant'
        elif self.role == 2:
            user_role = "Customer"
        
        return user_role


class UserProfile(models.Model):
    user = models.OneToOneField(User , on_delete=models.CASCADE)
    address = models.CharField(blank=True , max_length=250)
   
    profile_picture = models.ImageField(blank=True,upload_to='user/profile_pictures' )
    cover_picture = models.ImageField(blank=True,upload_to='user/cover_pictures' )
    city = models.CharField(blank=True , max_length=20)
    state = models.CharField(blank=True , max_length=20)
    country = models.CharField(blank=True , max_length=20 , default="INDIA")
    latitude = models.CharField(max_length=20 , blank=True)
    longitude = models.CharField(max_length=20 , blank = True)
    location = gismodels.PointField(blank=True , null=True , srid=4326)
    created_at =models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.user.first_name
    
    def save(self , *args , **kwargs):
        if self.longitude and self.longitude:
            self.location = Point(float(self.longitude) , float(self.latitude))
            return super(UserProfile , self).save(*args , **kwargs)
        return super(UserProfile , self).save(*args , **kwargs)

orders/models.py
from django.db import models
from accounts.models import User
from menu.models import FoodItem
from vendor.models import Vendor
import json
# Create your models here.

request_object = ''

class Payment(models.Model):
    PAYMENT_METHOD = (
        ('PAYPAL','PAYPAL'),
        ('RAZORPAY' , 'RAZORPAY')
)
    user = models.ForeignKey(User , on_delete=models.CASCADE)
    transaction_id = models.CharField(max_length=100)
    payment_method =models.CharField(max_length=100 ,choices=PAYMENT_METHOD)
    amount = models.CharField(max_length=10)
    status = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.transaction_id
    
class Order(models.Model):
    STATUS = (
        ('NEW','NEW'),
        ('ACCEPTED' , 'ACCEPTED'),
        ('COMPLETED' , 'COMPLETED'),
        ('CANCELLED' , 'CANCELLED'),

    )
    user = models.ForeignKey(User , on_delete=models.SET_NULL , null=True)
    payment = models.ForeignKey(Payment , on_delete=models.SET_NULL ,blank=True , null=True)
    vendors = models.ManyToManyField(Vendor , blank=True)
    order_number = models.CharField(max_length=20)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    phone = models.CharField(max_length=15 , blank=True)
    email = models.EmailField(max_length=50)
    address = models.CharField(max_length=200)
    country = models.CharField(max_length=15 , blank=True)
    state = models.CharField(max_length=15 , blank=True)
    city = models.CharField(max_length=50)
    pin_code = models.CharField(max_length=10)
    total = models.FloatField()
    tax_data = models.JSONField(blank=True , help_text="Data Format:{'tax_type':{'tax_percentage':'tax_amount'}}" , null=True)
    total_data = models.JSONField(blank=True , null=True)
    total_tax = models.FloatField()
    payment_method = models.CharField(max_length=25)
    status = models.CharField(max_length=15 , choices=STATUS , default='NEW')
    is_ordered = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now =True)

    @property
    def name(self):
        return f'{self.first_name} {self.last_name}'
    
    def __str__(self):
        return self.order_number
    def order_placed_to(self):
        return ", ".join([str(i) for i in self.vendors.all()])
    def get_total_by_vendor(self):
        vendor = Vendor.objects.get(user=request_object.user)
        if self.total_data:
            total_data = self.total_data
            sub_list = []
            for item in total_data:
                for key in item.keys():
                    # print(vendor.id)
                    # print(key)
                    if key == str(vendor.id):
                        sub_list.append(item[key])
            
            
            tax_amount=0
            for item1 in sub_list:
                for key2 , val in item1.items():
                    subtotal = float(key2)
                    tax_type = val['tax_type']
                    tax_amount += val['tax_amount']
                    tax_percentage = val['tax_percentage']
                    # print(tax_type , tax_amount , tax_percentage)
            grand_total = float(subtotal) + float(tax_amount)
            # print(subtotal , grand_total , tax_amount)
        return {
            'grand_total':grand_total , 
            'subtotal':subtotal,
            'tax_amount':tax_amount,
        }

class OrderFood(models.Model):
    order = models.ForeignKey(Order , on_delete=models.CASCADE)
    payment = models.ForeignKey(Payment , on_delete=models.CASCADE)
    user = models.ForeignKey(User , on_delete=models.CASCADE)
    fooditem = models.ForeignKey(FoodItem , on_delete=models.CASCADE)
    quantity = models.IntegerField()
    price = models.FloatField()
    amount = models.FloatField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now = True)
    def __str__(self):
        return self.fooditem.food_title

foodOnline/views.py
from django.shortcuts import render
from django.http import HttpResponse
from vendor.models import Vendor
from django.contrib.gis.geos import GEOSGeometry
from django.db.models import Q
from django.contrib.gis.measure import D
from django.contrib.gis.db.models.functions import Distance

def get_or_set_current_location(request):
    if 'lat' in request.session:
        lat = request.session['lat']
        long = request.session['long']
        return long,lat
    elif 'lat' in request.GET:
        lat = request.GET['lat']
        long = request.GET['long']
        request.session['lat'] = lat
        request.session['long'] = long
        return long,lat
    else:
        return None



def home(request):
    if get_or_set_current_location(request) is not None:
        pnt = GEOSGeometry('POINT(%s %s)' % (get_or_set_current_location(request)))
        vendors = Vendor.objects.filter( user_profile__location__distance_lte=(pnt , D(km=150))).annotate(distance=Distance("user_profile__location" , pnt)).order_by('distance')
        for v in vendors:
            v.kms = round(v.distance.km ,1 )
    else:
        vendors = Vendor.objects.filter(is_approved= True , user__is_active=True)[:8]
    # print(vendors)
    context = {
        'vendors':vendors,
    }
    return render(request , "home.html" , context)

foodOnline/templates/base.html
{% load static %}
<html lang="en">

<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>FoodOnline</title>
	<!-- Google Font Family Link Start -->
	<link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Montserrat:400,700">
	<link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Open+Sans:400,700,800">
	<!-- Google Font Family Link End -->

	<!-- CSS -->
	<link href="{% static 'css/iconmoon.css' %}" rel="stylesheet">
	<link href="{% static 'css/style.css' %}" rel="stylesheet">
	<link href="{% static 'css/cs-foodbakery-plugin.css' %}" rel="stylesheet">
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
	<link href="{% static 'css/bootstrap-slider.css' %}" rel="stylesheet">
	<link rel="stylesheet" href="{% static 'css/custom.css' %}">
	
	<!-- JAVASCRIPT -->
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
	<script src="{% static 'js/modernizr.js' %}"></script>
	<script src="{% static 'js/bootstrap.js' %}"></script>
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
	{% if '/' == request.path or 'vendor_profile' in request.path or 'customer_profile/' in request.path %}
	<script src="https://maps.googleapis.com/maps/api/js?key={{GOOGLE_API_KEY}}&libraries=places&callback=initAutoComplete"  defer></script>
	
	{% endif %}
	<script src="{% static 'js/custom.js' %}"></script>
	<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
	<script src="https://kit.fontawesome.com/5d1f4df922.js" crossorigin="anonymous"></script>
	<!-- PAYPAL INTEGRATION -->
	<script src="https://www.paypal.com/sdk/js?client-id=AQcvPXCRVL6gEcgQr7MUg4tH2rIEXdfTfHSsiCeOKe5Lz8eY9URmGC2--Ycw39z4bQgX2mkQ5EQprIN4&currency=USD"></script>
	<!-- Datatables plugin integration for my_orders Page -->
	<link rel="stylesheet" href="https://cdn.datatables.net/1.13.6/css/jquery.dataTables.min.css">
	<style>
		body, .main-section p, .mce-content-body p{
			font:Normal  14px/24px "Open Sans", sans-serif;letter-spacing: 0px;text-transform: none;color: #515151 !important;
		}
	</style>
</head>

	


<!-- LOAD NAVBAR HERE -->
{% include 'includes/header.html' %}


<!-- LOAD CONTENT HERE -->
{% block content %}
{% endblock %}


<!-- LOAD FOOTER  -->
{% include 'includes/footer.html' %}

foodOnline/templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<!-- Main Section Start -->
<div class="main-section">
	<!-- Home Pages Elements Strat -->
	<!-- Main Search Start -->
	<div class="page-section nopadding cs-nomargin"
		style="padding-top: 200px; padding-bottom: 150px; margin-bottom: 0px; background: url({% static 'extra-images/bg-image1.jpg' %}) no-repeat center / cover;">
		<div class="container">
			<div class="row">
				<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 ">
					<div class="element-title">
						<h1
							style="font-size: 40px; color: #505050; text-transform: uppercase; line-height: 50px; margin-bottom: 25px; text-align:center;">
							We are in the business of food<br>our restaurants do</h1>
						<p style="font-size: 18px; letter-spacing: 1px; color: #505050; text-align:center;" class="text-uppercase">
							Search for the top restaurants near you and enjoy a lipsmacking meal</p>
					</div>
				</div>
				<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 ">
					<div class="main-search fancy bg-holder ">
						<form action="{% url 'search' %}" method="get">
							<div class="row">
								<div class="col-lg-4 col-md-4 col-sm-3 col-xs-12">
									<div class="field-holder">
										<input type="text" name="keyword" placeholder="Resturant name or food items">
									</div>
								</div>
								<div class="col-lg-4 col-md-4 col-sm-5 col-xs-12">
									<div class="field-holder">
										<ul>
											<li class="select-location">
												<div class="foodbakery-locations-fields-group foodbakery-focus-out">
													<span class="foodbakery-search-location-icon"><i
															class="icon-location"></i></span>
													
													<input type="text" class="location-field-text filter"
														placeholder="All Locations" id="id_address" name='address' required>
													<input type="hidden"name='lat' value="" id="id_latitude">
													<input type="hidden"name='long' value="" id="id_longitude">
												</div>
												
											</li>
										</ul>
									</div>
								</div>
								<div class="col-lg-2 col-md-2 col-sm-2 col-xs-12 mb-1 ">
									<select name="radius" id="radius" class="h-100 text-black" required>
										<option value="" selected>Choose Radius</option>
										<option value="5">5km</option>
										<option value="10">10km</option>
										<option value="15">15km</option>
										<option value="25">25km</option>
										<option value="50">50km</option>
										<option value="75">75km</option>
									</select>
								</div>
								<div class="col-lg-2 col-md-2 col-sm-2 col-xs-12">
									<div class="field-holder">
										<input type="submit" value="Search">
									</div>
								</div>
							</div>
						</form>
					</div>
				</div>

			</div>
		</div>
	</div>
	<!-- Main Search End -->

	<!-- Top Restarurants Section Start -->
	<div class="page-section nopadding cs-nomargin"
		style="margin-top: 0px;padding-top: 60px;padding-bottom: 0px;margin-bottom: 0px;background: #ffffff;">
		<div class="container">
			<div class="row">
				<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
					<div class="element-title align-left">
						<h2>Top Restaurants</h2>
						<p>Explore restaurants, bars, and cafés by locality</p>
					</div>
				</div>
				<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
					<div class="company-logo">
						<ul>
							{% for vendor in vendors %}
							<li class="has-border">
								<figure>
									{% if vendor.user_profile.profile_picture %}
									<a href="{% url 'vendor_detail' vendor.vendor_slug %}"><img src="{{vendor.user_profile.profile_picture.url}}"
											class="attachment-full size-full wp-post-image" alt=""></a>
									{% else %}
									<a href="{% url 'vendor_detail' vendor.vendor_slug %}"><img src="{% static 'images/default-profile.PNG' %}" alt=""></a>
									{% endif %}
								</figure>
							</li>
							{% endfor %}
							
						</ul>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- Top Restarurants Section End -->
	<!-- Choose From Most Popular Listin Start -->
	<div class="page-section nopadding cs-nomargin"
		style="margin-top: 0px;padding-top: 60px;padding-bottom: 50px;margin-bottom: 0px;background: #ffffff;">
		<div class="container">
			<div class="row">
				<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
					<div class="element-title align-center">
						<h2>Choose From Most Popular Restaurants</h2>
						<p>Highest Rated Restarurants of the City</p>
					</div>
				</div>
				<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
					<div class="listing fancy">
						<ul class="row">
							{% for vendor in vendors %}
							<li class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
								<div class="list-post featured">
									<div class="img-holder">
										
										<figure><a href="{% url 'vendor_detail' vendor.vendor_slug %}">
											{% if vendor.user_profile.profile_picture %}
											<img src="{{vendor.user_profile.profile_picture.url}}"
													class="img-thumb wp-post-image" alt=""></a>
											{% else %}
											<img src="{% static 'images/default-profile.PNG' %}" alt="">
											{% endif %}

										</figure>
										{% if vendor.is_open %}
										<span class="restaurant-status open">
											<em class="bookmarkRibbon"></em>Open</span>
											{% else %}
											<span class="restaurant-status close">
												<em class="bookmarkRibbon"></em>Close</span>
											{% endif %}
										
									</div>
									<div class="text-holder">
										<div class="list-rating">
											<div class="rating-star">
												<span class="rating-box" style="width: 100%;"></span>
											</div>
											<span class="reviews">(1)</span>
										</div>
										<div class="post-title">
											<h5>
												<a href="{% url 'vendor_detail' vendor.vendor_slug %}">{{vendor}}</a>
												<span class="sponsored text-color">Sponsored</span>
											</h5>
										</div>
										{% if vendor.user_profile.address %}
										<address>{{vendor.user_profile.address}}</address>
										{% endif %}
										{% if vendor.kms %}
											<br>
											<span><small><b>{{vendor.kms}} Km From Your Location </b></small></span>
										
										{% endif %}
									</div>

								</div>
							</li>
							{% endfor %}



							
						</ul>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- Choose From Most Popular Listing End -->

	<!-- Home Pages Elements End  -->
</div>
{% endblock %}
<!-- Main Section End -->
<!-- Footer Start -->


<!-- Modal Popup End -->