foodOnline/urls.py
from django.contrib import admin
from django.urls import path , include
from . import views
from django.conf import settings
from django.conf.urls.static import static
from marketplace import views as mplace_views
urlpatterns = [
    path("admin/", admin.site.urls),
    path('' , views.home ,name='home'),
    path('accounts/' , include('accounts.urls')),
    path('vendor/' ,include('vendor.urls')),
    path('marketplace/' , include('marketplace.urls')),
    path('cart/' ,mplace_views.cart , name='cart'),
    #Search
    path('search/',mplace_views.search ,name = 'search'),
    path('customer/' , include('customers.urls')),
    path('checkout/' , mplace_views.checkout , name='checkout'),
    path('orders/' , include('orders.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

marketplace/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('' , views.marketplace , name='marketplace'),
    
    path('<slug:vendor_slug>/' , views.vendor_detail, name='vendor_detail'),
    # Add to cart Url
    path('add_to_cart/<int:food_id>/' , views.add_to_cart , name='add_to_cart'),
    # Decrease Cart 
    path('decrease_cart/<int:food_id>/' , views.decrease_cart ,name = 'decrease_cart'),
    #Delete Cart Items
    path('delete_cartitem/<int:cart_id>/' , views.delete_cartitem , name= 'delete_cartitem')
    
]

orders/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('place_order' , views.place_order , name='place_order'),
    path('payments/' , views.payments , name = 'payments'),
    path('order_complete/' , views.order_complete ,name ='order_complete'),
]

marketplace/models.py
from django.db import models
from accounts.models import User
from menu.models import FoodItem

# Create your models here.

class Cart(models.Model):
    user = models.ForeignKey(User  , on_delete=models.CASCADE)
    fooditem = models.ForeignKey(FoodItem , on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __unicode__(self):
        return self.user
    
    class Meta:
        verbose_name = "Cart"
        verbose_name_plural = "Cart"


class Tax(models.Model):
    tax_type= models.CharField(max_length= 20 , unique =True)
    tax_percentage =models.DecimalField(decimal_places=2 ,max_digits=4 , verbose_name='Tax Percentage (%)')
    is_active = models.BooleanField(default=True)
    class Meta:
        verbose_name_plural='Taxes'


    def __str__(self):
        return self.tax_type

        

menu/models.py
from django.db import models
from vendor.models import Vendor
# Create your models here.
class Category(models.Model):
    vendor = models.ForeignKey(Vendor , on_delete=models.CASCADE)
    category_name = models.CharField(max_length=50 )
    slug = models.SlugField(max_length=100, unique=True)
    description = models.TextField(max_length=250 , blank=True)
    created_at =models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now_add=True)
    class Meta:
        verbose_name = "Category"
        verbose_name_plural = "Categories"
    
    def clean(self):
        self.category_name = self.category_name.capitalize()

    def __str__(self):
        return self.category_name

class FoodItem(models.Model):
   vendor = models.ForeignKey(Vendor , on_delete=models.CASCADE)
   category = models.ForeignKey(Category , on_delete=models.CASCADE)
   food_title = models.CharField(max_length=100)
   slug = models.SlugField(max_length=150 , unique=True)
   description = models.TextField(max_length=250 ,blank=True)
   price = models.IntegerField()
   image = models.ImageField(upload_to='foodImages')
   is_available = models.BooleanField(default=True)
   created_at =models.DateTimeField(auto_now_add=True)
   updated_at = models.DateTimeField(auto_now_add=True)

   def __str__(self):
       return self.food_title

foodOnline/views.py
from django.shortcuts import render
from django.http import HttpResponse
from vendor.models import Vendor
from django.contrib.gis.geos import GEOSGeometry
from django.db.models import Q
from django.contrib.gis.measure import D
from django.contrib.gis.db.models.functions import Distance

def get_or_set_current_location(request):
    if 'lat' in request.session:
        lat = request.session['lat']
        long = request.session['long']
        return long,lat
    elif 'lat' in request.GET:
        lat = request.GET['lat']
        long = request.GET['long']
        request.session['lat'] = lat
        request.session['long'] = long
        return long,lat
    else:
        return None



def home(request):
    if get_or_set_current_location(request) is not None:
        pnt = GEOSGeometry('POINT(%s %s)' % (get_or_set_current_location(request)))
        vendors = Vendor.objects.filter( user_profile__location__distance_lte=(pnt , D(km=150))).annotate(distance=Distance("user_profile__location" , pnt)).order_by('distance')
        for v in vendors:
            v.kms = round(v.distance.km ,1 )
    else:
        vendors = Vendor.objects.filter(is_approved= True , user__is_active=True)[:8]
    # print(vendors)
    context = {
        'vendors':vendors,
    }
    return render(request , "home.html" , context)

marketplace/views.py
from django.shortcuts import render , redirect
from vendor.models import Vendor , OpeningHour
from django.http import HttpResponse , JsonResponse
from menu.models import FoodItem
from .models import Cart
from .context_processors import get_cart_counter , get_cart_amounts
from django.contrib.auth.decorators import login_required
from django.db.models import Q
# Geodjango modules
from django.contrib.gis.geos import GEOSGeometry
from django.contrib.gis.measure import D
from django.contrib.gis.db.models.functions import Distance
from datetime import date , datetime
from orders.forms import OrderForm
from django.shortcuts import get_object_or_404
from accounts.models import UserProfile


# Create your views here.
def marketplace(request):
    vendors = Vendor.objects.filter(is_approved = True , user__is_active=True)
    vendor_count = vendors.count()
    context = {
        'vendors':vendors,
        'vendor_count':vendor_count,
    }
    return render(request , 'marketplace/listings.html' , context)

def vendor_detail(request , vendor_slug):
    vendor = Vendor.objects.get(vendor_slug = vendor_slug)
    
    if request.user.is_authenticated:
        cartitems = Cart.objects.filter(user = request.user)
    else:
        cartitems = None
    openinghour = OpeningHour.objects.filter(vendor=vendor).order_by('day' , '-from_hour')
    today_date = date.today()
    today = today_date.isoweekday()
    today_opening_hours = OpeningHour.objects.filter(vendor=vendor , day = today)
    is_open = vendor.is_open()
        
    context = {
        'openinghour':openinghour,
        'vendor':vendor,
        'cartitems':cartitems,
        'today_opening_hours':today_opening_hours,
        'is_open':is_open,
    }
    return render(request , 'marketplace/vendor_detail.html' , context)

def add_to_cart(request , food_id):
    if request.user.is_authenticated:
        if request.headers.get('X-Requested-With') == 'XMLHttpRequest':
            try:
                fooditem = FoodItem.objects.get(id = food_id)
                try:
                    checkcart = Cart.objects.get(user = request.user , fooditem=fooditem)
                    # Increase cart Quantity
                    checkcart.quantity +=1
                    checkcart.save()
                    return JsonResponse({'status':'Success' ,'message':'Increased The Cart Quantity' , 'cart_counter':get_cart_counter(request) , 'qty':checkcart.quantity ,'cart_amount':get_cart_amounts(request)})
                except:
                    checkcart = Cart.objects.create(user=request.user , fooditem=fooditem , quantity =1 )
                    return JsonResponse({'status':'Success' , 'message':'New Item Added to Cart' , 'cart_counter':get_cart_counter(request) , 'qty':checkcart.quantity , 'cart_amount':get_cart_amounts(request)})
            except:
                return JsonResponse({'status':'Failed' ,'message':'Food Item Does not exists'})
        else:
            return JsonResponse({'status':'Failed' ,'message':'Invalid request'})
        
    
    else:
        return JsonResponse({'status':'login_required' ,'message':'Please Login to continue'})
    
def decrease_cart(request , food_id):
    if request.user.is_authenticated:
        if request.headers.get('X-Requested-With') == 'XMLHttpRequest':
            try:
                fooditem = FoodItem.objects.get(id = food_id)
                try:
                    checkcart = Cart.objects.get(user = request.user , fooditem=fooditem)
                    # decrease cart Quantity
                    if checkcart.quantity >1:
                        checkcart.quantity -=1
                        checkcart.save()
                        
                    else:
                        checkcart.delete()
                        checkcart.quantity=0  
                    return JsonResponse({'status':'Success'  , 'cart_counter':get_cart_counter(request) , 'qty':checkcart.quantity , 'cart_amount':get_cart_amounts(request)})
                except:
                    
                    return JsonResponse({'status':'Failed' , 'message':'You do not have this item in cart' })
            except:
                return JsonResponse({'status':'Failed' ,'message':'Food Item Does not exists'})
        else:
            return JsonResponse({'status':'Failed' ,'message':'Invalid request'})
        
    
    else:
        return JsonResponse({'status':'login_required' ,'message':'please login to continue'})
    
@login_required(login_url = 'login')
def cart(request):
    cartitems  = Cart.objects.filter(user=request.user).order_by('-created_at')
    context =  {
        'cartitems':cartitems,
    }
    return render(request ,'marketplace/cart.html' , context)

def delete_cartitem(request , cart_id):
    if request.user.is_authenticated:
        if request.headers.get('X-Requested-With') == 'XMLHttpRequest':
            try:
                cart_item = Cart.objects.get(user = request.user , id = cart_id)
                if cart_item:
                    cart_item.delete()
                    return JsonResponse({'status':'Success' , 'message':"Cart Item deleted succesfully " , "cart_counter":get_cart_counter(request) ,'cart_amount':get_cart_amounts(request)})
            except:
               return JsonResponse({'status':'Failed' ,'message':'Cart Item Does not exists'})
        else:
            return JsonResponse({'status':'Failed' , 'message':"Invalid Request"  })

# Search functionality on home page
def search(request):
    if request.method=='GET':
        keyword= request.GET['keyword']
        address = request.GET['address']
        lat = request.GET['lat']
        long = request.GET['long']
        radius = request.GET['radius']
        # get vendor id that has the user desired fooditem
        vendor_byFoodItem = FoodItem.objects.filter(Q(food_title__icontains=keyword , is_available=True)|Q(description__icontains=keyword , is_available=True)).values_list('vendor_id' , flat=True)
        vendors = Vendor.objects.filter(Q(id__in=list(set(vendor_byFoodItem))) |Q(vendor_name__icontains =keyword , is_approved=True , user__is_active=True))       
        if lat and long and radius:
            pnt = GEOSGeometry('POINT(%s %s)' % (long , lat))
            vendors = Vendor.objects.filter(Q(id__in=list(set(vendor_byFoodItem))) |Q(vendor_name__icontains =keyword , is_approved=True , user__is_active=True) , 
                                            user_profile__location__distance_lte=(pnt , D(km=radius))
                                            ).annotate(distance=Distance("user_profile__location" , pnt)).order_by('distance')
            for v in vendors:
                v.kms = round(v.distance.km ,1 )
        vendor_count = vendors.count()
        
        context = {
            'vendors':vendors,
            'vendor_count':vendor_count,
            'source_location':address,
        }
    
    return render(request , 'marketplace/listings.html' ,context)
@login_required(login_url = 'login')
def checkout(request):
    cart_items = Cart.objects.filter(user=request.user).order_by('created_at')
    cart_count = cart_items.count()
    
    if cart_count==0:
        return redirect('marketplace')
    user_profile = get_object_or_404(UserProfile , user=request.user)
    defaut_values = {
        'first_name':request.user.first_name,
        'last_name':request.user.last_name,
        'phone':request.user.phone_number,
        'email':request.user.email,
        'address':user_profile.address,
        'country':user_profile.country,
        'state':user_profile.state,
        'city':user_profile.city,
        
    }
    form = OrderForm(initial=defaut_values)
    context = {
        'form':form,
        'cart_items':cart_items,
       
    
    }
    return render(request , 'marketplace/checkout.html' , context)

foodOnline/templates/marketplace/cart.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<!-- This is cart.html  -->
<div class="page-section pt-5">
    <div class="container">
        <div class="row">
            <!-- Cart Items -->
            <div class="col-lg-8 col-md-8 col-sm-8 col-xs-12">
                <div class="tabs-holder horizontal">
                    <ul class="stickynav-tabs nav nav-tabs">
                        <li class="active"><a data-toggle="tab" href="#home"><i class="fa-solid fa-cart-shopping"></i>Cart Items</a></li>

                    </ul>
                    <div class="tab-content">
                        <div id="home" class="tab-pane in active">
                            <div class="menu-itam-holder">
                                <div class="text-center display-4 p-5 fw-bold d-none" id="empty-cart">Cart is Empty</div>

                                <div id="menu-item-list-6272" class="menu-itam-list">

                                    
                                    
                                    <ul>
                                    {% if cartitems %}
                                    {% for item in cartitems %}
                                        <li id="cart-item-{{item.id}}">
                                            <div class="image-holder"> <a href="#"><img src="{{ item.fooditem.image.url }}"
                                                        height='70px' alt=""></a></div>
                                            <div class="text-holder">
                                                <h6>{{item.fooditem}}</h6>
                                                <span>{{item.fooditem.description}}</span>
                                                <a href="{% url 'vendor_detail' item.fooditem.vendor.vendor_slug %}" class="badge text-bg-warning">{{item.fooditem.vendor}}</a>
                                            </div>
                                            <div class="price-holder">
                                                <span class="price">{{item.fooditem.price}}</span>
                                                <a href="#" data-id="{{item.fooditem.id}}"
                                                    data-url="{% url 'decrease_cart' item.fooditem.id %}" data-cart-id = "{{item.id}}" class="decrease_cart"
                                                    style="margin-right: 30px;"><i
                                                        class="icon-minus text-color"></i></a>
                                                <label for="" id="qty-{{item.fooditem.id}}">0</label>
                                                <a href="#" class="add_to_cart" data-id="{{item.fooditem.id}}"
                                                    data-url="{% url 'add_to_cart' item.fooditem.id %}"><i
                                                        class="icon-plus4 text-color fw-bold"></i></a>
                                                <a href="#" class="delete_to_cart" data-id="{{item.id}}"
                                                data-url="{% url 'delete_cartitem' item.id %}"><i  class="fa-solid fa-trash text-color"></i></a>
                                        
                                        

                                            </div>
                                        </li>
                                        
                                    {% endfor %}
                                    {% else %}
                                    <div class="text-center display-4 p-5 fw-bold">Cart is Empty</div>
                                    {% endif %}
                                    </ul>
                                    
                                    
                                   
                                    {% for item in cartitems %}
                                    <span id="qty-{{item.fooditem.id}}" class='item_qty d-none'
                                        data-qty='{{item.quantity}}' "></span>
                                    {% endfor %}
                                    
                                </div>
                            </div>
                            
                        </div>
                    </div>
                </div>
                
            </div>
            <!-- Your order section -->
            <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
                <div class="tabs-holder horizontal">
                    <ul class="stickynav-tabs nav nav-tabs">
                        <li class="active"><a data-toggle="tab" href="#home">
                                   <i class="fa-solid fa-money-bill"></i>Your Order</a></li>

                    </ul>
                    <div class="tab-content">
                        <div id="home" class="tab-pane in active">
                            <!-- <div class="menu-itam-holder"> -->
                                <div>
                                    <ul >
                                        <li class="list-unstyled">Subtotal
                                            <span class="price float-end pe-3">
                                                <span class="currency">$</span>
                                                <span id="subtotal">{{subtotal}}</span>
                                            </span>
                                        </li>
                                        {% for item in tax_list %}
                                            <li  class="list-unstyled">{{item.tax_type}}<small> {{item.tax_percentage}}%</small>
                                                <span class="price float-end pe-3">
                                                <span class="currency">$</span>
                                                <span id="tax-{{item.tax_type}}">{{item.tax_amount}}</span>
                                                </span>
                                            </li>
                                        {% endfor %}
                                        <li  class="list-unstyled">Total
                                            <span class="price float-end fw-bold pe-3">
                                                <span class="currency">$</span>
                                                <span id="total">{{grand_total}}</span>
                                            </span>
                                        </li>
                                        <a href="{% url 'checkout' %}" class="btn btn-danger w-75 p-2 m-3">Proceed to Checkout</a>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div> <!--Your Order Section end-->
            

        </div>
    </div>
</div>
{% endblock %}

foodOnline/templates/marketplace/vendor_detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="main-section">
    <div class="page-section restaurant-detail-image-section" style=" background: url({% if vendor.user_profile.cover_picture %} {{vendor.user_profile.cover_picture.url}} {% else %} {% static 'images/default-profile.PNG' %} {% endif %}) no-repeat scroll 0 0 / cover;">
        <!-- Container Start -->
        <div class="container">
            <!-- Row Start -->
            <div class="row">
                <!-- Column Start -->
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="company-info-detail">
                        <div class="company-info">
                            <div class="img-holder">
                                <figure>
                                    {% if vendor.user_profile.profile_picture %}
                                    <img src="{{vendor.user_profile.profile_picture.url}}" alt="">
                                    {% else %} 
                                    <img src="{% static 'images/default-profile.PNG' %}" alt=""> 
                                    {% endif %}
                                </figure>
                            </div>
                            <div class="text-holder">
                                <span class="h3 text text-white">{{vendor | capfirst}}{% if is_open %}(OPEN){% else %}(CLOSED){% endif %}</span>
                                <div class="text">
                                    <i class="icon-local_pizza"></i>
                                    <p>{{vendor.user_profile.address}}</p>
                                </div>
                            </div>
                        </div>
                        <div class="delivery-timing reviews-sortby">
                            {% if openinghour %}
                            <ul>
                                <li>
                                    <a href="#" class="reviews-sortby-active">
                                        <span>Today :</span>
                                        {% for i in today_opening_hours %}
                                        <span>
                                            {% if i.is_closed %}
                                            Closed
                                            {% else %}
                                            {{i.from_hour}} - {{i.to_hour}}
                                        </span>
                                        {% endif %}
                                        
                                        {% endfor %}
                                        <i class="icon-chevron-small-down"></i>
                                    </a>
                                    <ul class="delivery-dropdown">
                                        {% for hour in openinghour %}
                                        <li><a href="#"><span class="opend-day">{{hour}}</span> <span class="opend-time"><small>:</small>{% if hour.is_closed %}Closed{% else %}{{hour.from_hour}}-{{hour.to_hour}}{% endif %}</span></a></li>
                                        {% endfor %}
                                        
                                    </ul>
                                </li>
                            </ul>
                            {% endif %}
                        </div>
                        
                    </div>
                </div>
                <!-- Column End -->
            </div>
            <!-- Row End -->
        </div>
        <!-- Container End -->
    </div>

    <div class="page-section">
        <div class="container">
            <div class="row">
                <div class="col-lg-3 col-md-3 col-sm-4 col-xs-12 sticky-sidebar">
                    <div class="filter-toggle">
                        <span class="filter-toggle-text">Categories By</span><i class="icon-chevron-down"></i>
                    </div>
                    <div class="filter-wrapper">
                        <div class="categories-menu">
                            <h6><i class="icon-restaurant_menu"></i>Categories</h6>
                            <ul class="menu-list">
                                {% for v_cat in vendor.category_set.all %}
                                <li class="active"><a href="#" class="menu-category-link">{{v_cat}}</a></li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="col-lg-9 col-md-9 col-sm-8 col-xs-12">
                    <div class="tabs-holder horizontal">
                        <ul class="stickynav-tabs nav nav-tabs">
                            <li class="active"><a data-toggle="tab" href="#home"><i class="icon- icon-room_service"></i>Menu</a></li>
                            
                        </ul>
                        <div class="tab-content">
                            <div id="home" class="tab-pane in active">
                                <div class="menu-itam-holder">
                                    
                                    <div id="menu-item-list-6272" class="menu-itam-list">
                                        
                                        {% for v_cat in vendor.category_set.all %}
                                        <div class="element-title" id="menu-category-2">
                                            <h5 class="text-color">{{v_cat}}</h5>
                                            <span>{{v_cat.description}}</span>
                                        </div>
                                        {% for food in v_cat.fooditem_set.all %}
                                        {% if food.is_available %}
                                        <ul>
                                            <li>
                                                <div class="image-holder"> <a href="#"><img src="{{ food.image.url }}"  height = '70px' alt=""></a></div>
                                                <div class="text-holder">
                                                    <h6>{{food}}</h6>
                                                    <span>{{food.description}}</span>
                                                </div>
                                                <div class="price-holder">
                                                    <span class="price">{{food.price}}</span>
                                                    <a href="{% url 'decrease_cart' food.id %}" data-id ="{{food.id}}" data-url="{% url 'decrease_cart' food.id %}" class="decrease_cart" style="margin-right: 30px;"><i class="icon-minus text-color"></i></a>
                                                    <label for="" id="qty-{{food.id}}">0</label>
                                                    <a href="#" class="add_to_cart" data-id ="{{food.id}}" data-url="{% url 'add_to_cart' food.id %}" ><i class="icon-plus4 text-color fw-bold"></i></a>
                                                   
                                                </div>
                                            </li>
                                        {% endif %}
                                            
                                        </ul>
                                        {% endfor %}
                                        {% endfor %}
                                        {% for item in cartitems %}
                                        <span id = "qty-{{item.fooditem.id}}" class='item_qty d-none' data-qty='{{item.quantity}}' "></span>
                                        {% endfor %}
                                    </div>
                                </div>
                            </div>
                            
                        </div>
                    </div>
                </div>
                
            </div>
        </div>
    </div>
</div>
{% endblock %}